<a href="https://colab.research.google.com/github/Vyankatesh-ops/Machine-Learning/blob/main/Exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Employee.csv')
df.shape

(148, 6)

In [3]:
df

Company   Age  Salary     Place Country  Gender
0        TCS  20.0     NaN   Chennai   India       0
1    Infosys  30.0     NaN    Mumbai   India       0
2        TCS  35.0  2300.0  Calcutta   India       0
3    Infosys  40.0  3000.0     Delhi   India       0
4        TCS  23.0  4000.0    Mumbai   India       0
..       ...   ...     ...       ...     ...     ...
143      TCS  33.0  9024.0  Calcutta   India       1
144  Infosys  22.0  8787.0  Calcutta   India       1
145  Infosys  44.0  4034.0     Delhi   India       1
146      TCS  33.0  5034.0    Mumbai   India       1
147  Infosys  22.0  8202.0    Cochin   India       0

[148 rows x 6 columns]

In [4]:
df.duplicated().sum()

np.int64(4)

In [5]:
df.drop_duplicates(inplace=True)
df.shape

(144, 6)

In [6]:
df.reset_index(inplace=True)
df.drop('index',axis=1,inplace=True)
df

Company   Age  Salary     Place Country  Gender
0                TCS  20.0     NaN   Chennai   India       0
1            Infosys  30.0     NaN    Mumbai   India       0
2                TCS  35.0  2300.0  Calcutta   India       0
3            Infosys  40.0  3000.0     Delhi   India       0
4                TCS  23.0  4000.0    Mumbai   India       0
..               ...   ...     ...       ...     ...     ...
139  Infosys Pvt Lmt  22.0  8202.0    Mumbai   India       0
140              TCS  33.0  9024.0  Calcutta   India       1
141          Infosys  44.0  4034.0     Delhi   India       1
142              TCS  33.0  5034.0    Mumbai   India       1
143          Infosys  22.0  8202.0    Cochin   India       0

[144 rows x 6 columns]

In [7]:
df.head(5)

Company   Age  Salary     Place Country  Gender
0      TCS  20.0     NaN   Chennai   India       0
1  Infosys  30.0     NaN    Mumbai   India       0
2      TCS  35.0  2300.0  Calcutta   India       0
3  Infosys  40.0  3000.0     Delhi   India       0
4      TCS  23.0  4000.0    Mumbai   India       0

In [8]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Company  136 non-null    object 
 1   Age      127 non-null    float64
 2   Salary   121 non-null    float64
 3   Place    130 non-null    object 
 4   Country  144 non-null    object 
 5   Gender   144 non-null    int64  
dtypes: float64(2), int64(1), object(3)
memory usage: 6.9+ KB


In [9]:
df.isna().sum()

Company     8
Age        17
Salary     23
Place      14
Country     0
Gender      0
dtype: int64

In [10]:
df.columns

Index(['Company', 'Age', 'Salary', 'Place', 'Country', 'Gender'], dtype='object')

In [11]:

unique=df.nunique()
unique

Company     6
Age        29
Salary     40
Place      11
Country     1
Gender      2
dtype: int64

In [12]:
df['Company'].unique()

array(['TCS', 'Infosys', 'CTS', nan, 'Tata Consultancy Services',
       'Congnizant', 'Infosys Pvt Lmt'], dtype=object)

In [13]:
df['Company'].replace('Infosys Pvt Lmt','Infosys',inplace=True)
df['Company'].replace('Tata Consultancy Services','TCS',inplace=True)
df['Company'].replace('CTS','Congnizant',inplace=True)
df['Company'].replace('Congnizant','Cognizant',inplace=True)
df['Company'].unique()

/tmp/ipython-input-4075095943.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Company'].replace('Infosys Pvt Lmt','Infosys',inplace=True)
/tmp/ipython-input-4075095943.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace

array(['TCS', 'Infosys', 'Cognizant', nan], dtype=object)

In [14]:
df['Age'].unique()

array([20., 30., 35., 40., 23., nan, 34., 45., 18., 22., 32., 37., 50.,
       21., 46., 36., 26., 41., 24., 25., 43., 19., 38., 51., 31., 44.,
       33., 17.,  0., 54.])

In [15]:
df['Salary'].unique()

array([  nan, 2300., 3000., 4000., 5000., 6000., 7000., 8000., 9000.,
       1089., 1234., 3030., 3045., 3184., 4824., 5835., 7084., 8943.,
       8345., 9284., 9876., 2034., 7654., 2934., 4034., 5034., 8202.,
       9024., 4345., 6544., 6543., 3234., 4324., 5435., 5555., 8787.,
       3454., 5654., 5009., 5098., 3033.])

In [16]:

df['Place'].unique()

array(['Chennai', 'Mumbai', 'Calcutta', 'Delhi', 'Podicherry', 'Cochin',
       nan, 'Noida', 'Hyderabad', 'Bhopal', 'Nagpur', 'Pune'],
      dtype=object)

In [17]:
df['Gender'].unique()

array([0, 1])

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe=OneHotEncoder()

In [20]:
df_array=ohe.fit_transform(df[['Company','Place','Gender']]).toarray()
df_array

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [21]:
ohe.categories_

[array(['Cognizant', 'Infosys', 'TCS', nan], dtype=object),
 array(['Bhopal', 'Calcutta', 'Chennai', 'Cochin', 'Delhi', 'Hyderabad',
        'Mumbai', 'Nagpur', 'Noida', 'Podicherry', 'Pune', nan],
       dtype=object),
 array([0, 1])]

In [23]:
single_list=[innerlistone for main_array in ohe.categories_ for innerlistone in main_array]
single_list

['Cognizant',
 'Infosys',
 'TCS',
 nan,
 'Bhopal',
 'Calcutta',
 'Chennai',
 'Cochin',
 'Delhi',
 'Hyderabad',
 'Mumbai',
 'Nagpur',
 'Noida',
 'Podicherry',
 'Pune',
 nan,
 np.int64(0),
 np.int64(1)]

In [24]:
df_new=pd.DataFrame(df_array,columns=single_list)
df_new

Cognizant  Infosys  TCS  NaN  Bhopal  Calcutta  Chennai  Cochin  Delhi  \
0          0.0      0.0  1.0  0.0     0.0       0.0      1.0     0.0    0.0   
1          0.0      1.0  0.0  0.0     0.0       0.0      0.0     0.0    0.0   
2          0.0      0.0  1.0  0.0     0.0       1.0      0.0     0.0    0.0   
3          0.0      1.0  0.0  0.0     0.0       0.0      0.0     0.0    1.0   
4          0.0      0.0  1.0  0.0     0.0       0.0      0.0     0.0    0.0   
..         ...      ...  ...  ...     ...       ...      ...     ...    ...   
139        0.0      1.0  0.0  0.0     0.0       0.0      0.0     0.0    0.0   
140        0.0      0.0  1.0  0.0     0.0       1.0      0.0     0.0    0.0   
141        0.0      1.0  0.0  0.0     0.0       0.0      0.0     0.0    1.0   
142        0.0      0.0  1.0  0.0     0.0       0.0      0.0     0.0    0.0   
143        0.0      1.0  0.0  0.0     0.0       0.0      0.0     1.0    0.0   

     Hyderabad  Mumbai  Nagpur  Noida  Podicherry  Pune  NaN    0    1  
0          0.0     0.0     0.0    0.0         0.0   0.0  0.0  1.0  0.0  
1          0.0     1.0     0.0    0.0         0.0   0.0  0.0  1.0  0.0  
2          0.0     0.0     0.0    0.0         0.0   0.0  0.0  1.0  0.0  
3          0.0     0.0     0.0    0.0         0.0   0.0  0.0  1.0  0.0  
4          0.0     1.0     0.0    0.0         0.0   0.0  0.0  1.0  0.0  
..         ...     ...     ...    ...         ...   ...  ...  ...  ...  
139        0.0     1.0     0.0    0.0         0.0   0.0  0.0  1.0  0.0  
140        0.0     0.0     0.0    0.0         0.0   0.0  0.0  0.0  1.0  
141        0.0     0.0     0.0    0.0         0.0   0.0  0.0  0.0  1.0  
142        0.0     1.0     0.0    0.0         0.0   0.0  0.0  0.0  1.0  
143        0.0     0.0     0.0    0.0         0.0   0.0  0.0  1.0  0.0  

[144 rows x 18 columns]

In [25]:

df_ml=pd.concat([df,df_new],axis=1)
df_ml

Company   Age  Salary     Place Country  Gender  Cognizant  Infosys  TCS  \
0        TCS  20.0     NaN   Chennai   India       0        0.0      0.0  1.0   
1    Infosys  30.0     NaN    Mumbai   India       0        0.0      1.0  0.0   
2        TCS  35.0  2300.0  Calcutta   India       0        0.0      0.0  1.0   
3    Infosys  40.0  3000.0     Delhi   India       0        0.0      1.0  0.0   
4        TCS  23.0  4000.0    Mumbai   India       0        0.0      0.0  1.0   
..       ...   ...     ...       ...     ...     ...        ...      ...  ...   
139  Infosys  22.0  8202.0    Mumbai   India       0        0.0      1.0  0.0   
140      TCS  33.0  9024.0  Calcutta   India       1        0.0      0.0  1.0   
141  Infosys  44.0  4034.0     Delhi   India       1        0.0      1.0  0.0   
142      TCS  33.0  5034.0    Mumbai   India       1        0.0      0.0  1.0   
143  Infosys  22.0  8202.0    Cochin   India       0        0.0      1.0  0.0   

     NaN  ...  Delhi  Hyderabad  Mumbai  Nagpur  Noida  Podicherry  Pune  NaN  \
0    0.0  ...    0.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
1    0.0  ...    0.0        0.0     1.0     0.0    0.0         0.0   0.0  0.0   
2    0.0  ...    0.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
3    0.0  ...    1.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
4    0.0  ...    0.0        0.0     1.0     0.0    0.0         0.0   0.0  0.0   
..   ...  ...    ...        ...     ...     ...    ...         ...   ...  ...   
139  0.0  ...    0.0        0.0     1.0     0.0    0.0         0.0   0.0  0.0   
140  0.0  ...    0.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
141  0.0  ...    1.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
142  0.0  ...    0.0        0.0     1.0     0.0    0.0         0.0   0.0  0.0   
143  0.0  ...    0.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   

       0    1  
0    1.0  0.0  
1    1.0  0.0  
2    1.0  0.0  
3    1.0  0.0  
4    1.0  0.0  
..   ...  ...  
139  1.0  0.0  
140  0.0  1.0  
141  0.0  1.0  
142  0.0  1.0  
143  1.0  0.0  

[144 rows x 24 columns]

In [26]:
df_ml


Company   Age  Salary     Place Country  Gender  Cognizant  Infosys  TCS  \
0        TCS  20.0     NaN   Chennai   India       0        0.0      0.0  1.0   
1    Infosys  30.0     NaN    Mumbai   India       0        0.0      1.0  0.0   
2        TCS  35.0  2300.0  Calcutta   India       0        0.0      0.0  1.0   
3    Infosys  40.0  3000.0     Delhi   India       0        0.0      1.0  0.0   
4        TCS  23.0  4000.0    Mumbai   India       0        0.0      0.0  1.0   
..       ...   ...     ...       ...     ...     ...        ...      ...  ...   
139  Infosys  22.0  8202.0    Mumbai   India       0        0.0      1.0  0.0   
140      TCS  33.0  9024.0  Calcutta   India       1        0.0      0.0  1.0   
141  Infosys  44.0  4034.0     Delhi   India       1        0.0      1.0  0.0   
142      TCS  33.0  5034.0    Mumbai   India       1        0.0      0.0  1.0   
143  Infosys  22.0  8202.0    Cochin   India       0        0.0      1.0  0.0   

     NaN  ...  Delhi  Hyderabad  Mumbai  Nagpur  Noida  Podicherry  Pune  NaN  \
0    0.0  ...    0.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
1    0.0  ...    0.0        0.0     1.0     0.0    0.0         0.0   0.0  0.0   
2    0.0  ...    0.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
3    0.0  ...    1.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
4    0.0  ...    0.0        0.0     1.0     0.0    0.0         0.0   0.0  0.0   
..   ...  ...    ...        ...     ...     ...    ...         ...   ...  ...   
139  0.0  ...    0.0        0.0     1.0     0.0    0.0         0.0   0.0  0.0   
140  0.0  ...    0.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
141  0.0  ...    1.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   
142  0.0  ...    0.0        0.0     1.0     0.0    0.0         0.0   0.0  0.0   
143  0.0  ...    0.0        0.0     0.0     0.0    0.0         0.0   0.0  0.0   

       0    1  
0    1.0  0.0  
1    1.0  0.0  
2    1.0  0.0  
3    1.0  0.0  
4    1.0  0.0  
..   ...  ...  
139  1.0  0.0  
140  0.0  1.0  
141  0.0  1.0  
142  0.0  1.0  
143  1.0  0.0  

[144 rows x 24 columns]

In [27]:
df.to_csv('Employee_cleaned.csv',index=False)

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:

label=LabelEncoder()
print(label)

LabelEncoder()


In [30]:
df_sample=pd.read_csv('Employee_cleaned.csv')
df_sample['Company']=label.fit_transform(df_sample['Company'])

In [31]:

df_sample

Company   Age  Salary     Place Country  Gender
0          2  20.0     NaN   Chennai   India       0
1          1  30.0     NaN    Mumbai   India       0
2          2  35.0  2300.0  Calcutta   India       0
3          1  40.0  3000.0     Delhi   India       0
4          2  23.0  4000.0    Mumbai   India       0
..       ...   ...     ...       ...     ...     ...
139        1  22.0  8202.0    Mumbai   India       0
140        2  33.0  9024.0  Calcutta   India       1
141        1  44.0  4034.0     Delhi   India       1
142        2  33.0  5034.0    Mumbai   India       1
143        1  22.0  8202.0    Cochin   India       0

[144 rows x 6 columns]

In [32]:
df

Company   Age  Salary     Place Country  Gender
0        TCS  20.0     NaN   Chennai   India       0
1    Infosys  30.0     NaN    Mumbai   India       0
2        TCS  35.0  2300.0  Calcutta   India       0
3    Infosys  40.0  3000.0     Delhi   India       0
4        TCS  23.0  4000.0    Mumbai   India       0
..       ...   ...     ...       ...     ...     ...
139  Infosys  22.0  8202.0    Mumbai   India       0
140      TCS  33.0  9024.0  Calcutta   India       1
141  Infosys  44.0  4034.0     Delhi   India       1
142      TCS  33.0  5034.0    Mumbai   India       1
143  Infosys  22.0  8202.0    Cochin   India       0

[144 rows x 6 columns]

In [33]:
data=df.iloc[ : ,[1,2]]
data

Age  Salary
0    20.0     NaN
1    30.0     NaN
2    35.0  2300.0
3    40.0  3000.0
4    23.0  4000.0
..    ...     ...
139  22.0  8202.0
140  33.0  9024.0
141  44.0  4034.0
142  33.0  5034.0
143  22.0  8202.0

[144 rows x 2 columns]

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:

scaler=StandardScaler().fit(data)
print(scaler)

StandardScaler()


In [36]:
data_scaled=scaler.transform(data)

In [37]:
print(data_scaled)

[[-0.95092413         nan]
 [-0.04765289         nan]
 [ 0.40398273 -1.15877891]
 [ 0.85561834 -0.88689921]
 [-0.67994276 -0.49849963]
 [        nan -0.11010005]
 [        nan  0.27829953]
 [-0.67994276  0.66669911]
 [ 0.3136556   1.0550987 ]
 [ 1.30725396  1.44349828]
 [-0.67994276         nan]
 [ 0.3136556  -1.62913081]
 [ 1.30725396         nan]
 [-1.13157837 -1.57281287]
 [ 0.85561834 -0.88689921]
 [-0.67994276 -0.88689921]
 [-0.67994276 -0.87524722]
 [ 0.3136556  -0.11010005]
 [-0.77026988         nan]
 [ 0.13300136         nan]
 [ 0.58463697 -0.86942123]
 [ 1.75888958 -0.81543368]
 [-0.860597   -0.17845837]
 [        nan  0.2142136 ]
 [        nan  0.69932468]
 [-0.67994276  1.4213595 ]
 [ 0.3136556   1.18909655]
 [ 1.30725396  1.55380376]
 [-0.67994276  1.78373631]
 [ 0.40398273 -1.2620932 ]
 [ 1.39758109  0.92071244]
 [-0.95092413 -0.91253358]
 [ 1.30725396 -0.48529404]
 [ 0.49430985 -0.09689446]
 [-0.40896139  1.13355541]
 [ 0.40398273  1.45281987]
 [ 0.13300136         nan]
 

In [38]:
scaled_data_set=pd.DataFrame(data_scaled,columns=data.columns)
scaled_data_set

Age    Salary
0   -0.950924       NaN
1   -0.047653       NaN
2    0.403983 -1.158779
3    0.855618 -0.886899
4   -0.679943 -0.498500
..        ...       ...
139 -0.770270  1.133555
140  0.223328  1.452820
141  1.216927 -0.485294
142  0.223328 -0.096894
143 -0.770270  1.133555

[144 rows x 2 columns]

In [39]:
data=df.iloc[ : ,[1,2]]
data

Age  Salary
0    20.0     NaN
1    30.0     NaN
2    35.0  2300.0
3    40.0  3000.0
4    23.0  4000.0
..    ...     ...
139  22.0  8202.0
140  33.0  9024.0
141  44.0  4034.0
142  33.0  5034.0
143  22.0  8202.0

[144 rows x 2 columns]

In [40]:
from sklearn.preprocessing import MinMaxScaler

In [41]:

scaler=MinMaxScaler().fit(data)
print(scaler)

MinMaxScaler()


In [42]:
scaler.data_min_

array([   0., 1089.])

In [43]:
scaler.data_max_

array([  54., 9876.])

In [44]:
data.describe()

Age       Salary
count  127.000000   121.000000
mean    30.527559  5283.471074
std     11.114717  2585.373600
min      0.000000  1089.000000
25%     22.000000  3030.000000
50%     33.000000  5000.000000
75%     37.500000  8000.000000
max     54.000000  9876.000000

In [45]:
scaler.feature_range

(0, 1)

In [46]:
data_scaled_mm=scaler.transform(data)

In [47]:

print(data_scaled_mm)

[[0.37037037        nan]
 [0.55555556        nan]
 [0.64814815 0.13781723]
 [0.74074074 0.21748037]
 [0.42592593 0.33128485]
 [       nan 0.44508934]
 [       nan 0.55889382]
 [0.42592593 0.6726983 ]
 [0.62962963 0.78650279]
 [0.83333333 0.90030727]
 [0.42592593        nan]
 [0.62962963 0.        ]
 [0.83333333        nan]
 [0.33333333 0.01650165]
 [0.74074074 0.21748037]
 [0.42592593 0.21748037]
 [0.42592593 0.2208945 ]
 [0.62962963 0.44508934]
 [0.40740741        nan]
 [0.59259259        nan]
 [0.68518519 0.22260157]
 [0.92592593 0.23842039]
 [0.38888889 0.42505975]
 [       nan 0.54011608]
 [       nan 0.68225788]
 [0.42592593 0.89382042]
 [0.62962963 0.82576534]
 [0.83333333 0.93262775]
 [0.42592593 1.        ]
 [0.64814815 0.10754524]
 [0.85185185 0.74712644]
 [0.37037037 0.20996927]
 [0.83333333 0.33515421]
 [0.66666667 0.44895869]
 [0.48148148 0.80949129]
 [0.64814815 0.90303858]
 [0.59259259        nan]
 [0.64814815        nan]
 [0.62962963 0.13781723]
 [0.75925926 0.21748037]
